codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
        if_not_found: success
        informational: false
        only_pulls: false
    patch:
      default:
        target: 90%
        threshold: 2%
        base: auto
        if_not_found: success
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "tests/**"
  - "examples/**"
  - "benchmark.py"
  - "setup.py"
  - "**/__init__.py"
  - "**/test_*.py"