repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format

- repo: local
  hooks:
  - id: smart-linting
    name: Smart Linting Fixes
    entry: python scripts/pre_commit_smart_fix.py
    language: python
    always_run: true
    pass_filenames: false
    additional_dependencies: []
