repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
  - id: ruff
    name: ruff lint
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
    name: ruff format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0
  hooks:
  - id: mypy
    additional_dependencies: [torch>=2.0.0, einops>=0.8.0]
    files: ^dilated_attention_pytorch/
    args: [--ignore-missing-imports, --no-strict-optional]