[project]
name = "dilated-attention-pytorch"
version = "0.1.0"
description = ""
authors = [
    {name = "Michael Harris",email = "mharris021@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
