name: Test

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"

      - name: Install Hatch
        run: |
          pip install --upgrade pip
          pip install hatch

      - name: Install Dependencies
        run: |
          # Install CPU-only PyTorch for CI
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          # Install package with test dependencies
          pip install -e .[test]

      - name: Format Check
        run: |
          hatch run format
          # Check if formatting changed any files
          git diff --exit-code

      - name: Lint
        run: |
          hatch run lint

      - name: Type Check
        run: |
          hatch run typecheck

      - name: Test
        run: |
          hatch run test-cov

      - name: Upload coverage
        if: matrix.python == '3.11'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  test-gpu:
    name: GPU Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install hatch
          # Note: In a real CI with GPU, you'd install CUDA PyTorch
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e .[test]

      - name: Run GPU Tests (Mock)
        run: |
          # In real CI with GPU runners, this would run actual GPU tests
          echo "GPU tests would run here with proper hardware"
          # pytest tests/ -m gpu