name: Test

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        python: ["3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"

      - name: Install Hatch
        run: |
          pip install --upgrade pip
          pip install hatch

      - name: Install Dependencies
        run: |
          # Install CPU-only PyTorch for CI
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          # Install package with test dependencies
          pip install -e .[test]

      - name: Format Check
        run: |
          hatch run format-check
          
      - name: Lint
        run: |
          hatch run lint

      - name: Type Check
        run: |
          hatch run typecheck

      - name: Test
        run: |
          hatch run test-cov

      - name: Upload coverage to Codecov
        if: matrix.python == '3.13'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
          
      - name: Generate coverage report
        if: matrix.python == '3.13'
        run: |
          pip install coverage[toml]
          coverage html
          
      - name: Upload coverage HTML report
        if: matrix.python == '3.13'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

  test-gpu:
    name: GPU Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    container:
      image: pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
      options: --gpus all
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Check GPU availability
        run: |
          python -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}')"
          python -c "import torch; print(f'CUDA device count: {torch.cuda.device_count()}')"
          nvidia-smi || echo "nvidia-smi not available"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install hatch
          # Install CUDA-enabled PyTorch
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
          pip install -e .[test,cuda]

      - name: Run GPU Tests
        run: |
          # Run tests marked as requiring GPU
          pytest tests/ -m gpu -v --tb=short
          
      - name: Run GPU Benchmarks
        run: |
          # Run a quick benchmark to verify GPU performance
          python -m pytest tests/test_dilated_attention.py::test_forward -v --benchmark-only --benchmark-min-rounds=10